name: CI
on:  [workflow_dispatch, pull_request, push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.SA_KEY }}'
  
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: Download secure file from gsutil
        run: | 
          gsutil cp gs://rechat-data/file_a.jsonl nbs/
          gsutil cp gs://rechat-data/file_a.jsonl nbs/

      - name: Look
        run: |
          ls -l nbs/

      - uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.version }}
          cache: "pip"
          cache-dependency-path: settings.ini
  
      - name: Test with nbdev
        env:
          USE_PRE: ''
          SKIP_TEST: ''
          FLAGS: ''
          TORCH_CPU: true
        shell: bash
        run: |
          set -ux
          python -m pip install --upgrade pip
          if [ $USE_PRE ]; then
            pip install -U git+https://github.com/fastai/fastcore.git
            pip install -U git+https://github.com/fastai/ghapi.git
            pip install -U git+https://github.com/fastai/execnb.git
            pip install -U git+https://github.com/fastai/nbdev.git
          else
            pip install -U nbdev
          fi
          echo "Doing editable install..."
          if [ $TORCH_CPU ]; then
            test -f setup.py && pip install -e ".[dev]" --extra-index-url https://download.pytorch.org/whl/cpu
          else
            test -f setup.py && pip install -e ".[dev]"
          fi
          echo "Check we are starting with clean git checkout"
          if [[ `git status --porcelain -uno` ]]; then
            git diff
            echo "git status is not clean"
            false
          fi
          echo "Trying to strip out notebooks"
          nbdev_clean
          echo "Check that strip out was unnecessary"
          git status -s # display the status to see which nbs need cleaning up
          if [[ `git status --porcelain -uno` ]]; then
            git status -uno
            echo -e "!!! Detected unstripped out notebooks\n!!!Remember to run nbdev_install_hooks"
            echo -e "This error can also happen if you are using an older version of nbdev relative to what is in CI.  Please try to upgrade nbdev with the command `pip install -U nbdev`"
            false
          fi
          nbdev_export
          if [[ `git status --porcelain -uno` ]]; then
            echo "::error::Notebooks and library are not in sync.  Please run nbdev_export."
            git status -uno
            git diff
            exit 1;
          fi
          if [ ! $SKIP_TEST ]; then
            nbdev_test --flags "$FLAGS"
          fi

